extend tests

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -5,12 +5,24 @@ on:
 
 jobs:
   runTests:
-    runs-on: ubuntu-latest
+    runs-on: ${{ matrix.os }}
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [ macos-latest, ubuntu-latest ]
     steps:
       - name: Set up JDK
         uses: actions/setup-java@v1
         with:
           java-version: '11'
+      - name: Install Docker
+        if: ${{ matrix.os == 'macos-latest' }}
+        run: |
+          HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask docker
+          sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
+          open -a /Applications/Docker.app --args --unattended --accept-license
+          echo "We are waiting for Docker to be up and running. It can take over 2 minutes..."
+          while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
       - name: Set up Docker Buildx
         id: buildx
         uses: docker/setup-buildx-action@v1
@@ -18,6 +30,8 @@ jobs:
         uses: docker/setup-qemu-action@v1
       - name: Checkout
         uses: actions/checkout@v2
-      - name: Run tests
+      - name: Run Unit Tests
         run: |
-          ./gradlew test
+          ./gradlew unitTests
+      - name: Run Functional Tests
+          ./gradlew functionalTests
